# Generated by Django 4.2.2 on 2023-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_operations_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='notice',
            field=models.TextField(null=True),
        ),
    ]
