# Generated by Django 4.2.2 on 2023-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_operations_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='name_of_product_id',
            new_name='name_of_product',
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='operations',
            old_name='stuff_id',
            new_name='stuff',
        ),
        migrations.AddField(
            model_name='operations',
            name='notice',
            field=models.TextField(null=True),
        ),
    ]
