# Generated by Django 4.2.2 on 2023-07-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('calc', '0007_remove_operations_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProducts',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.products')),
            ],
            options={
                'verbose_name': 'Credit Product',
                'verbose_name_plural': 'Credit Products',
                'db_table': 'credit_products',
            },
            bases=('calc.products',),
        ),
        migrations.AlterModelOptions(
            name='stuff',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='operations',
            name='deb_cred',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='fk_name_of_product',
        ),
        migrations.AddField(
            model_name='operations',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operations',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
